# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b61f5dd986bdb7c5feca9ab4758139fdd2d03298afb1128c4dcb1816b2ba83a50ed0ceb3fe9662f279a61e266eed716e0dbcd85a53615ddb98302e0a0bc8dd8

test:
  secret_key_base: 22b5920342f9b455d351b05c8cb1fa2b6dd39eeda1236f9f0a43a623d182352a523de437bbbf6d240c4f0f7a197a76403da99cedd1415bc613918f55e525d0b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
